# Generated by Django 3.1.2 on 2020-10-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('timeofday', models.CharField(max_length=2)),
                ('itemid1', models.PositiveIntegerField()),
                ('itemid2', models.PositiveIntegerField()),
                ('itemid3', models.PositiveIntegerField(blank=True)),
                ('itemid4', models.PositiveIntegerField(blank=True)),
                ('itemid5', models.PositiveIntegerField(blank=True)),
                ('itemid6', models.PositiveIntegerField(blank=True)),
                ('itemid7', models.PositiveIntegerField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
