# Generated by Django 3.1.2 on 2020-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
