# Generated by Django 3.1.2 on 2020-10-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_auto_20201012_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='category',
        ),
    ]
