# Generated by Django 3.1.2 on 2020-10-13 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0007_auto_20201013_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='routine',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
