# Generated by Django 3.1.2 on 2020-10-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0008_auto_20201013_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
