# Generated by Django 3.1.2 on 2020-10-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0009_auto_20201013_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
