# Generated by Django 3.1.2 on 2020-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0011_auto_20201014_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
