# Generated by Django 3.1.2 on 2020-10-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0017_auto_20201016_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='itemid1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemid1', to='routines.item'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='itemid2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemid2', to='routines.item'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='itemid3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemid3', to='routines.item'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='itemid4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemid4', to='routines.item'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='itemid5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemid5', to='routines.item'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='itemid6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemid6', to='routines.item'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='itemid7',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemid7', to='routines.item'),
        ),
    ]
